force-app/main/default/objects/UIInstruction__e/UIInstruction__e.object-meta.xml
<CustomObject>
    <label>UIInstruction</label>
    <pluralLabel>UIInstructions</pluralLabel>
</CustomObject>

force-app/main/default/objects/UIInstruction__e/fields/Command__c.field-meta.xml
<CustomField>
    <fullName>Command__c</fullName>
    <label>Command</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UIInstruction__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PromptViaUserInterfaceAction.cls
public with sharing class PromptViaUserInterfaceAction {
    @InvocableMethod(
        label='Prompt via User Interface'
        description='Prompt something in User Interface (LWC)'
    )
    public static List<Boolean> promptViaUserInterface(
        List<Id> recordIds
    ) {
        if (recordIds.size() > 1) {
            System.debug('Currently only one recordIds per action (bulkification is not supported)');
        }
        System.debug(recordIds);
        EventBus.publish(
            new UIInstruction__e(Command__c = 'showAccountInfo', RecordId__c = recordIds[0])
        );
        return new List<Boolean>{ true };
    }
}