force-app/main/default/objects/UIInstruction__e/UIInstruction__e.object-meta.xml
<CustomObject>
    <label>UIInstruction</label>
    <pluralLabel>UIInstructions</pluralLabel>
</CustomObject>

force-app/main/default/objects/UIInstruction__e/fields/Command__c.field-meta.xml
<CustomField>
    <fullName>Command__c</fullName>
    <label>Command</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UIInstruction__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ShowSalesTrendTableAction.cls
public with sharing class ShowSalesTrendTableAction {
    public class DisplayRequest {
        @InvocableVariable(
            label='Start Date'
            description='Start Date of the trending period'
            required=true
        )
        public Date startDate;
        @InvocableVariable(
            label='End Date'
            description='End Date of the trending period'
            required=true
        )
        public Date endDate;
    }

    @InvocableMethod(
        label='Show sales trend table to user'
        description='Show sales trend table to user via Lightning UI'
    )
    public static List<Boolean> showSalesTrendTable(
        List<DisplayRequest> requests 
    ) {
        if (requests.size() > 1) {
            System.debug('Currently only one request per action (bulkification is not supported)');
        }
        String paramsJSON = JSON.serialize(requests[0]);
        EventBus.publish(
            new UIInstruction__e(Command__c = 'showSalesTrend', Parameters__c = paramsJSON)
        );
        return new List<Boolean>{ true };
    }
}