force-app/main/default/objects/UIInstruction__e/UIInstruction__e.object-meta.xml
<CustomObject>
    <label>UIInstruction</label>
    <pluralLabel>UIInstructions</pluralLabel>
</CustomObject>

force-app/main/default/objects/UIInstruction__e/fields/Command__c.field-meta.xml
<CustomField>
    <fullName>Command__c</fullName>
    <label>Command</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UIInstruction__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SetHeighlightThresholdAction.cls
public with sharing class SetHeighlightThresholdAction {
    @InvocableMethod(
        label='Set Heighlight Threshold value of sales trend table'
        description='Set Heighlight Threshold value of sales trend table'
    )
    public static List<Boolean> setHeighlightThreshold(
        List<Integer> highlightThresholds
    ) {
        if (highlightThresholds.size() > 1) {
            System.debug('Currently only one highlightThresholds per action (bulkification is not supported)');
        }
        System.debug(highlightThresholds);
        String paramsJSON = JSON.serialize(new Map<String, Object>{ 'threshold' => highlightThresholds[0] });
        EventBus.publish(
            new UIInstruction__e(Command__c = 'setHeighlightThreshold', Parameters__c = paramsJSON)
        );
        return new List<Boolean>{ true };
    }
}